name: college-quiz-app
services:
    nginx-server:
        build: .
        ports:
            - "80:80"
        restart: unless-stopped
        volumes:
            - "./backend/storage/logs:/var/www/college-quiz-app/storage/logs"

    redis:
        image: redis:alpine
        privileged: true
        command: [ "sh", "-c", "sysctl vm.overcommit_memory=1 && redis-server" ]
        ports:
            - "6379:6379"
        restart: unless-stopped
        volumes:
            - "./redis-data:/data"
