export default {
    dashboard: 'Tổng quan',
    subjects: 'Môn học',
    courses: 'Khóa học',
    schoolClass: 'Lớp học',
    faculty: 'Khoa',
    profile: 'Cá nhân',
    exams: 'Bài thi',
    questions: 'Câu hỏi',
    teachers: 'Giáo viên',
    students: 'Học sinh',
    permission: 'Phân quyền',
    semester: 'Học kỳ',
    settings: 'Cài đặt',
    term: 'Điều khoản',
    privacy: 'Riêng tư',
    security: 'Bảo mật',
    contact: 'Liên hệ',
    docs: 'Tài liệu',
};
