export default {
    create: 'Tạo bài thi',
    name: 'Tên',
    examDate: 'Ngày thi',
    examTime: 'Thời gian',
    totalQuestions: 'Tổng số câu hỏi',
    questions: 'Câu hỏi',
    save: 'Lưu',
    maxChapterQuestionCount: 'Chương @name chỉ có @questionNumber câu hỏi.',
    supervisors: 'Giám thị',
    search: 'Tìm kiếm',
    joinedSupervisors: 'Giám thị đã tham gia',
    allSupervisors: 'Toàn bộ giám thị',
    numberOfExpertQuestions: 'Số lượng câu rất khó',
    numebrOfHardQuestions: 'Số lượng câu khó',
    numberOfMediumQuestion: 'Số lượng câu trung bình',
};
