export default {
    dashboard: 'Dashboard',
    subjects: 'Subjects',
    courses: 'Course',
    schoolClass: 'School Class',
    faculty: 'Faculty',
    profile: 'Profile',
    exams: 'Exam',
    archives: 'Archives',
    questions: 'Questions',
    admins: 'Admins',
    teachers: 'Teachers',
    students: 'Students',
    permission: 'Permission',
    semester: 'Semester',
    settings: 'Settings',
    term: 'Term',
    privacy: 'Privacy',
    security: 'Security',
    contact: 'Contact',
    docs: 'Docs',
};
