export default {
	exam: 'Exam',
	name: 'Name',
	examDate: 'Exam Date',
	examTime: 'Exam Time',
	totalQuestions: 'Total questions',
	questions: 'Questions',
	supervisors: 'Supervisors',
	search: 'Search',
	joinedSupervisors: 'Joined Supervisors',
	allSupervisors: 'All Supervisors',
	save: 'Save',
	delete: 'Delete',
	maxChapterQuestionCount: 'Chapter @name has only @questionNumber questions.',
	deleteMessage: 'Are you sure you want to delete this exam? This action cannot be undone.',
	langYes: 'Yes',
	langNo: 'No',
};
