export default {
    create: 'Create Exam',
    name: 'Name',
    examDate: 'Exam Date',
    examTime: 'Exam Time',
    totalQuestions: 'Total questions',
    questions: 'Questions',
    save: 'Save',
    maxChapterQuestionCount: 'Chapter @name has only @questionNumber questions.',
    supervisors: 'Supervisors',
    search: 'Search',
    joinedSupervisors: 'Joined Supervisors',
    allSupervisors: 'All Supervisors',
    numberOfExpertQuestions: 'Number of expert questions',
    numebrOfHardQuestions: 'Number of hard questions',
    numberOfMediumQuestion: 'Number of medium questions',
};
