export default {
	forgotPassword: 'Forgot Password',
	emailSentTo: 'We have sent a recovery code to',
	enterEmail: 'Please enter your email address below',
	enterRecoveryCode: 'Please enter the recovery code below',
	enterNewPassword: 'Enter a new password below',
	email: 'Email',
	recoveryCode: 'Recovery Code',
	password: 'Password',
	confirmPassword: 'Confirm Password',
	sendCode: 'Send Code',
	verify: 'Verify',
	save: 'Save',
	didNotReceiveEmail: 'Did not receive the email?',
	resend: 'Resend',
};
