name: vsc-dc
services:
    college-quiz-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
            - "3000:3000"
        command: sleep infinity
        volumes:
            - ../:/workspaces
