export default {
	exam: 'Bài thi',
	name: 'Tên',
	examDate: 'Ngày thi',
	examTime: 'Thời gian',
	totalQuestions: 'Tổng số câu hỏi',
	questions: 'Câu hỏi',
	supervisors: 'Giám thị',
	search: 'Tìm kiếm',
	joinedSupervisors: 'Giám thị đã tham gia',
	allSupervisors: 'Toàn bộ giám thị',
	save: 'Lưu',
	delete: 'Xóa',
	maxChapterQuestionCount: 'Chương @name chỉ có @questionNumber câu hỏi.',
	deleteMessage: 'Bạn có chắc chắn muốn xóa bài thi này? Hành động này không thể hoàn tác.',
	langYes: 'Có',
	langNo: 'Không',
};
