export default {
	shortcode: 'Mã số',
	teacher: 'Giáo viên',
	subject: 'Môn học',
	name: 'Tên',
	save: 'Lưu',
	delete: 'Xóa',
	deleteMessage: 'Bạn có chắc chắn muốn xóa khóa học này? Hành động này không thể hoàn tác.',
	langYes: 'Có',
	langNo: 'Không',
	studentList: 'Danh sách sinh viên',
	examtList: 'Danh sách bài thi',
	edit: 'Chỉnh sửa',
	add: 'Thêm',
	numberOfQuesions: '@number câu hỏi',
	minutes: '@number phút',
};
