export default {
	exam: 'Bài thi',
	name: 'Tên',
	examDate: 'Ngày thi',
	examTime: 'Thời gian',
	totalQuestions: 'Tổng số câu hỏi',
	questions: 'Câu hỏi',
	supervisors: 'Giám thị',
	langYes: 'Có',
	langNo: 'Không',
	startMessage: 'Bắt đầu bài thi ngay?',
	cancelMessage: 'Hủy bài thi ngay?',
	startExam: 'Bắt đầu bài thi',
	cancelExam: 'Hủy bài thi',
	doExam: 'Làm bài thi',
	result: 'Kết quả',
	refresh: 'Làm mới',
	schoolClass: 'Lớp',
	genders: {
		male: 'Nam',
		female: 'Nữ',
		gender: 'Giới tính'
	},
	score: 'Điểm số',
	didNotSubmitted: 'Chưa nộp bài',
};
