export default {
	exam: 'Exam',
	name: 'Name',
	examDate: 'Exam Date',
	examTime: 'Exam Time',
	totalQuestions: 'Total Questions',
	questions: 'Questions',
	supervisors: 'Supervisors',
	langYes: 'Yes',
	langNo: 'No',
	startMessage: 'Start the exam now?',
	cancelMessage: 'Cancel the exam now?',
	startExam: 'Start Exam',
	cancelExam: 'Cancel Exam',
	doExam: 'Take Exam',
	result: 'Result',
	refresh: 'Refresh',
	schoolClass: 'Class',
	genders: {
		male: 'Male',
		female: 'Female',
		gender: 'Gender'
	},
	score: 'Score',
	didNotSubmitted: 'Not submitted',
};
