export default {
	shortcode: 'Shortcode',
	teacher: 'Teacher',
	subject: 'Subject',
	name: 'Name',
	save: 'Save',
	delete: 'Delete',
	deleteMessage: 'Are you sure you want to delete this chapter? This action cannot be undone.',
	langYes: 'Yes',
	langNo: 'No',
	studentList: 'Student list',
	examtList: 'Exam list',
	edit: 'Edit',
	add: 'Add',
	numberOfQuesions: '@number questions',
	minutes: '@number minutes',
};
