<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TokenAbility extends Model
{
    use HasFactory;
    const ADMIN = [
        'admin',
        'student:view',
        'student:create',
        'student:update',
        'student:delete',
        //
        'teacher:view',
        'teacher:create',
        'teacher:update',
        'teacher:delete',
        //
        'subject:view',
        'subject:create',
        'subject:update',
        'subject:delete',
        //
        'chapter:view',
        'chapter:create',
        'chapter:update',
        'chapter:delete',
        //
        'semester:view',
        'semester:create',
        'semester:update',
        'semester:delete',
        //
        'course:view',
        'course:create',
        'course:update',
        'course:delete',
        //
        'enrollment:view',
        'enrollment:create',
        'enrollment:update',
        'enrollment:delete',
    ];
    const TEACHER = [
        'student:view',
        'student:create',
        'student:update',
        'student:delete',
        //
        'teacher:view',
        'teacher:create',
        'teacher:update',
        'teacher:delete',
        //
        'subject:view',
        'subject:create',
        'subject:update',
        'subject:delete',
        //
        'chapter:view',
        'chapter:create',
        'chapter:update',
        'chapter:delete',
        //
        'semester:view',
        'semester:create',
        'semester:update',
        'semester:delete',
        //
        'course:view',
        'course:create',
        'course:update',
        'course:delete',
        //
        'enrollment:view',
        'enrollment:create',
        'enrollment:update',
        'enrollment:delete',
    ];
    const STUDENT = [
        'student:view',
        'student:create',
        'student:update',
        'student:delete',
        //
        'teacher:view',
        'teacher:create',
        'teacher:update',
        'teacher:delete',
        //
        'subject:view',
        'subject:create',
        'subject:update',
        'subject:delete',
        //
        'chapter:view',
        'chapter:create',
        'chapter:update',
        'chapter:delete',
        //
        'semester:view',
        'semester:create',
        'semester:update',
        'semester:delete',
        //
        'course:view',
        'course:create',
        'course:update',
        'course:delete',
        //
        'enrollment:view',
        'enrollment:create',
        'enrollment:update',
        'enrollment:delete',
    ];
}
